<?php 

$slogan = 'молодая команда';
$pod_slogan = 'Быстро выполнит ваши задачи!';
$learn_more = 'УЗНАТЬ БОЛЬШЕ';

$qualitatively = 'ХОРОШОЕ КАЧЕСТВО';
$fast = 'БЫСТРАЯ РАБОТА';
$cheap = 'ДОСТУПНАЯ ЦЕНА';

$about = 'О нас';
$about_bottom = 'Мы молодая перспективная команда, которая целенаправленно занимается в сфере "веб-разработка". <br> Работая с нами вы получите наиболее удобный и современный сайт, за короткое время и доступную цену.';
$site1 = 'Информационный сайт';
$description_site1 = 'Информационный сайт - это ориентированный на внешнюю аудиторию сайт, который создает присутствие организации в сети Интернет. Первоочередной задачей такого сайта является представление бренда организации потенциальным клиентам.';
$site2 = 'Интернет-магазин';
$description_site2 = 'Это место в интернете, с помощью которого происходит прямая продажа товаров потребителю (юридическому или физическому лицу), включая доставку. При этом размещение потребительской информации, заказ товара и сделка происходят там же, внутри сети (на сайте интернет-магазина).';
$site3 = 'Сайт-визитка';
$description_site3 = 'Это полноценный интернет-ресурс, как правило, состоит из страницы, содержит основную информацию о компании, ее деятельности, предлагаемые товары или услуги, особенности и способы обратной связи. Грамотно разработанный сайт-визитка становится визитной карточкой, эффективной рекламой, круглосуточным офисом, лицом компании в Интернете.';

$our_works = 'Наши работы';
$description_work = 'Здесь вы можете увидеть образцы наших работ';
$name_site1 = 'Мой <span>Методист</span>';
$description_name_site1 = 'Информационный сайт, с помощью которого вы можете информировать посетителей.';
$name_site2 = 'Агро<span>База</span>';
$description_name_site2 = 'Интернет-магазин, где проводится прямая продажа товаров.';
$name_site3 = 'Гуртова <span>База</span>';
$description_name_site3 = 'CRM-система под определенные бизнес-задачи клиента.';

$sequence = 'Последовательность сотрудничества с нами';
$sequence_item_1 = 'У вас есть потребность в квалифицированных программистах?';
$sequence_item_1_1 = 'Жодного випадку про невиконаний до кінця проект.';
$sequence_item_1_2 = 'Після перегляду вами нашого сайта, Ви складаєте аналіз оцінку про те чи саме від нас Вам потрібна робота.';
$sequence_item_2 = "Свяжитесь с нами для обсуждения вопросов по вашему проекту.";
$sequence_item_2_1 = "Зв'язаться з нами Ви можете внизу сайта в контактній формі, або ж зателефонавути нам на гарячу лінію.";
$sequence_item_3 = 'Команда работает над поставленной задачей.';
$sequence_item_3_1 = 'Після обговорення з';
$sequence_item_4 = 'Ваше тестирования проекта.';
$sequence_item_4_1 = 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.';
$sequence_item_5 = 'Оплата и запуск сайта.';
$sequence_item_5_1 = 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.';

$argument = 'Почему мы?';
$argument_description1= 'Мы ответственно ставимся к своей работе, так как в ответе за нее.';
$argument_description2 = 'Мы уже долгое время работаем в этой сфере.';
$argument_description3 = 'Мы делаем быстро и качественно.';

$conctakt_form = 'Контактная форма';
$conctakt_description = 'Здесь вы можете задать интересующий вас вопрос, или же связаться с нами для заказа работы.';
$conctakt_name = ' ваше имя';
$conctakt_email = ' ваш email';
$conctakt_comment = ' ваш коментарий';
$conctakt_send = 'Отправить';

$our_address = 'Наш адрес';
$city1 = 'г. Киев ';
$city2 = 'г. Ровно ';
$phone = 'тел';
$conect = 'Связаться с нами';

 ?>