<?php 
$errore = $this->get('errore');
?>
<div class="content position-table admin-page">
	<?php if (!isset($_SESSION['login_admin'])) {            
		?>
		<div class="authorization-block">
			<?php if (!empty($errorsl)) { ?>
			<div>
				<span style="color:red	;"><?php echo $errorsl; ?></span>
			</div> 
			<?php } ?>
			<br/>
			<img src="../img/preload.png" alt="MyFreelancer">
			<form action="<?php echo base_url .'admin'; ?>" method="post">
				<input class="admin-int" type="text" name="login" placeholder=" ваш логін" value="<?php echo @$_POST['login']; ?>" /><br/><br/>
				<input class="admin-int" type="password" name="password" placeholder=" ваш пароль"/><br/><br/>
				<input type="submit" name="log" value="Увійти" />
			</form>
		</div>
		<?php }
		else { ?>
	<div style="float: left;margin-top: 30px;">
		
		<?php 
		if (!empty($errore)) echo "<div style='color: red;'>" .$errore ."</div>"; 
			if (empty($errore)) {
				if (!empty($_POST)) {
					echo "<div style='color: green;'>Користувач \"".$_POST['login']."\" успішно доданий!</div>";
				}
			}
			?>
		</div>
		<div>
			<form action="<?php echo base_url .'admin/add_users';?>" method="post">
				<table class="add-table">
					<tr class="table-top">
						<td class="width-name">Логін</td>
						<td>Пароль</td>
						<td>Пітвердження пароля</td>
					</tr>
					<tr>
						<td> <input type="text" name="login" value="<?php echo @$_POST['login']; ?>"> </td>
						<td> <input type="text" name="password" value="<?php echo @$_POST['password']; ?>"> </td>
						<td> <input type="text" name="password-confirm" value="<?php echo @$_POST['password-confirm']; ?>"> </td>			
					</tr>
					<input class="sub-save add_password" type="submit" name="add" value=" Додати">
				</table>
				<input type="hidden" name="date" value="<?php echo date('Y-m-d') ?>" />
				<br/><br/><br/><br/><br/>
				
				
			</form>
			
		</div>
		<?php } ?>
	</div>