<?php 
$errore = $this->get('errore');
?>
<div style="margin-top: 80px;">
	<div style="float: left;margin-top: 30px;">
		<?php 
		if (!empty($errore)) echo "<div style='color: red;'>" .$errore ."</div>"; 
			if (empty($errore)) {
				if (!empty($_POST)) {
					echo "<div style='color: green;'>Користувач \"".$_POST['login']."\" успішно доданий!</div>";
				}
			}
			?>
		</div>
		<div>
			<form action="<?php echo base_url .'admin/add_users';?>" method="post">
				<table class="add-table">
					<tr class="table-top">
						<td class="width-name">Логін</td>
						<td>Пароль</td>
						<td>Пітвердження пароля</td>
					</tr>
					<tr>
						<td> <input type="text" name="login" value="<?php echo @$_POST['login']; ?>"> </td>
						<td> <input type="text" name="password" value="<?php echo @$_POST['password']; ?>"> </td>
						<td> <input type="text" name="password-confirm" value="<?php echo @$_POST['password-confirm']; ?>"> </td>			
					</tr>
					<input class="sub-save" type="submit" name="add" value=" Добавити">
				</table>
				<input type="hidden" name="date" value="<?php echo date('Y-m-d') ?>" />
				<br/><br/><br/><br/><br/>
				
				
			</form>
		</div>
	</div>