<?php 
$result = $this->get('result');
$num = $this->get('num');
$errorsl = $this->get('errorsl');
?>

<div class="admin-page" style="margin-top: 80px;">
	
	<?php if (!isset($_SESSION['login_admin'])) {            
		?>
		<div class="authorization-block">
			<?php if (!empty($errorsl)) { ?>
			<div>
				<span style="color:red	;"><?php echo $errorsl; ?></span>
			</div> 
			<?php } ?>
			<br/>
			<img src="../img/preload.png" alt="MyFreelancer">
			<form action="<?php echo base_url .'admin'; ?>" method="post">
				<input class="admin-int" type="text" name="login" placeholder=" ваш логін" value="<?php echo @$_POST['login']; ?>" /><br/><br/>
				<input class="admin-int" type="password" name="password" placeholder=" ваш пароль"/><br/><br/>
				<input type="submit" name="log" value="Увійти" />
			</form>
		</div>
		<?php }
		else { ?>

		<div class="content position-table">
			<div class="user_panel">
				<a title="Повідомлення" class="admin_message users" href="<?php echo base_url .'admin'; ?>"><i class="fas fa-envelope"></i></a>
				<a title="Користувачі" class="admin_user users" href="<?php echo base_url .'admin/users'; ?>"><i class="fas fa-cog"></i></a>
				<a href="admin/logout">Exit</a>
			</div>

			<?php if (!isset($_GET['message']) && !isset($_GET['delete'])) {?>

			<table>
				<h2>Вхідні повідомлення</h2>
				<tr class="table-top">
					<td>Ім'я</td>
					<td>Email</td>
					<td class="width_row">Повідомлення</td>
					<td>Дата</td>
					<td>Дія</td>
				</tr>
				<?php while ($row = mysqli_fetch_array($result)) {?>
				
				<tr class="<?php if ($row['stan_massage'] == 'Непрочитано') { echo 'unread';} else { echo 'read';}?>" >
					<td onclick="window.location.href='<?php echo base_url .'/admin?message&id='.$row['id']; ?>'; return false"><?php echo ' '.$row['name_client']; ?></td>
					<td onclick="window.location.href='<?php echo base_url .'/admin?message&id='.$row['id']; ?>'; return false"><?php echo $row['email_client']; ?></td>
					<td onclick="window.location.href='<?php echo base_url .'/admin?message&id='.$row['id']; ?>'; return false"><?php $coment_client = $row['coment_client'];
					$counttext = 50;
					$coment_client = substr($coment_client, 0, $counttext);
					$coment_client = rtrim($coment_client);
					$coment_client = substr($coment_client, 0, strrpos($coment_client, ' '));
					if (mb_strlen($row['coment_client']) > $counttext) {
						echo $coment_client; 
					} else {
						echo $row['coment_client'];
					}   ?>
				</td>
				<td onclick="window.location.href='<?php echo base_url .'/admin?message&id='.$row['id']; ?>'; return false"><?php echo $row['date']; ?></td>
				<td class="center_text"><a href="<?php echo base_url .'admin?delete&id='.$row['id']; ?>"><i class="fas fa-trash-alt"></i></a></td>
			</tr>
			<?php } ?>
		</table>

		<?php }
		else
		{
			$roww = $this->get('roww');
			if (isset($_GET['message'])) {?>
			<div class="content position-table message-block">
				<div class="message-block-padd">
					<h2><?php echo $roww['name_client']; ?></h2><br><hr>
					<h4 class="left-position"><?php echo $roww['email_client']; ?></h4>
					<span class="right-position"><?php echo $roww['date'].' о '.$roww['time']; ?></span><br><br>
					<span><?php echo $roww['coment_client']; ?></span>
				</div>
			</div>
			<?php }

			if (isset($_GET['delete'])) {
				?>
				<div class="delete_message zatmenie">
					<div class="centr-block">
						<form action="<?php echo base_url .'admin?delete&id='.$roww['id']; ?>" method="post">
							Ви дійсно хочете <span style="color: red;">видалити</span> дане повідомлення!!!<br/><br/>
							<button type="submit" class="confirmation-btn" name="delete_tovar" value="1">Так</button>
							<button type="submit" class="confirmation-btn" name="delete_tovar" value="0">Ні</button>
						</form>
					</div>
				</div>

				<?php } 
			} 
		}?>
	</div>
</div>