<?php
if (isset($_SESSION['lang'])) {
	if ($_SESSION['lang'] == 'ru') {
		require_once('language/ru/templates/header.phtml');
	}
	if ($_SESSION['lang'] == 'en') {
		require_once('language/en/templates/header.phtml');
	}
	if ($_SESSION['lang'] == 'ua') {
		require_once('language/ua/templates/header.phtml');
	}
} else {
	require_once('language/ru/templates/header.phtml');
}
?>

<div class="content_resize">
	<div class="header">
		<div class="logo">
			<a href="/"><img src="img/logo.png" alt="Logo"></a>
		</div>
		<div class="langbar">
			<?php $redirect = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>
			<form action="/index" method="post" enctype="multipart/form-data">
				<ul class="lang"><?php echo $language; ?>   <i class="fas fa-chevron-down"></i>
					<ul class="sub-lang">
						<li><button type="submit" name="ru" value="ru">Русский</button></li>
						<li><button type="submit" name="en" value="en">English</button></li>
						<li><button type="submit" name="ua" value="ua">Українська</button></li>
					</ul>
				</ul>
				<input type="hidden" name="redirect" value="<?php echo $redirect;?>">
			</form>
		</div> 
		{{$headerMenu}}
	</div>
</div>