<div class="container">
        <h1>Гуртова <span style="font-weight: bold">База</span></h1>
        <div id="galery">
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_1.png"><img src="../img/hurtovabaza/mini/Screenshot_1.png" alt=""></a>
                        <figcaption>Сторінка входу</figcaption>
                    </img>
                </figure>
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_2.png"><img src="../img/hurtovabaza/mini/Screenshot_2.png" alt=""></a>
                        <figcaption>Головна сторінка</figcaption>
                    </img>
                </figure>
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_3.png"><img src="../img/hurtovabaza/mini/Screenshot_3.png" alt=""></a>
                        <figcaption>Добавлення товару</figcaption>
                    </img>
                </figure>
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_4.png"><img src="../img/hurtovabaza/mini/Screenshot_4.png" alt=""></a>
                        <figcaption>Дії з товарами</figcaption>
                    </img>
                </figure>
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_5.png"><img src="../img/hurtovabaza/mini/Screenshot_5.png" alt=""></a>
                        <figcaption>Сторінка налаштування</figcaption>
                    </img>
                </figure>
            <figure class="photo"><a data-lightbox="roadtrip" href="../img/hurtovabaza/Screenshot_6.png"><img src="../img/hurtovabaza/mini/Screenshot_6.png" alt=""></a>
                <figcaption>Сторінка розприділення</figcaption>
        </div>
