<html doctype="html">
<head>
    <title>{{$title}}</title>
    <meta name="title" content="{{$title}}" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta description="услуги вашой фирмы компании" keywords="ключевые слова">
    {{$headfiles}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="shortcut icon" href="/img/icon.png" type="image/x-icon">
    <link rel="stylesheet" href="../styles/media.css" media="screen">
    <link rel="stylesheet" href="../styles/lightbox.min.css">
    <link rel="stylesheet" href="../styles/demo-modals.css">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script type="text/javascript">
       $(document).ready(function(){
        $("#menu, #more").on("click","a", function (event) {
            event.preventDefault();
            var id  = $(this).attr('href'),
            top = $(id).offset().top;
            $('body,html').animate({scrollTop: top}, 800);
        });
    });
</script>
<script type="text/javascript" src="../script/jquery.the-modal.js"></script>
</head>
<body class="lock">

    {{$header}}
    {{$content}}
    {{$footer}}
<script type="text/javascript" src="../js/lightbox-plus-jquery.min.js"></script>
</body>
</html>