<?php 

$slogan = 'YOUND TEAM';
$pod_slogan = 'Quickly accomplish your tasks!';
$about = 'About us';

$qualitatively = 'GOOD QUALITY';
$fast = 'QUICK JOB';
$cheap = 'AVIABLE PRICE ';
$about_bottom = 'We are a promising young team that will make you the site most convenient and up-to-date, in a short time and an acceptable amount.';

$our_works = 'Our works';
$description_work = 'Here you can see the samples of our works.';
$name_site1 = 'My Methodist';
$site1 = 'Information site';
$name_site2 = 'AgroBaza';
$site2 = 'Online store';
$name_site3 = 'MYFREELANCER';
$site3 = 'Website card';

$argument = 'Why us?';
$argument_description1= 'We are responsibly preparing for our work, because in the answer for it.';
$argument_description2 = 'We have long been working in this field.';
$argument_description3 = 'We do quickly and qualitatively.';

$conctakt_form = 'Contact form';
$conctakt_description = 'Here you can ask a question interesting you, or contact us for the order of work.';
$conctakt_name = ' Your name';
$conctakt_email = ' Your email';
$conctakt_comment = ' Your comment';
$conctakt_send = 'Send';

$our_address = 'Our address';
$city1 = 'Kyiv ';
$city2 = 'Rovno';
$phone = 'phone num';
$conect = 'Connect with us';

 ?>