<?php 

$slogan = 'yound team';
$pod_slogan = 'Quickly accomplish your tasks!';
$learn_more = 'LEARN MORE';

$qualitatively = 'GOOD QUALITY';
$fast = 'QUICK JOB';
$cheap = 'AVIABLE PRICE ';

$about = 'Want a site?';
$about_bottom = 'We are a young and promising team, which is purposefully engaged in the field of "web development". <br> Working with us, you will get the most convenient and modern site, in a short time and affordable price.';
$site1 = 'Information site';
$description_site1 = "Information Website - This is an external-oriented site that creates the presence of an organization on the Internet. The primary goal of this site is to present the brand to the organization's potential customers.";
$site2 = 'Online store';
$description_site2 = 'This is a place on the Internet, through which there is a direct sale of goods to the consumer (legal or physical person), taking into account the delivery. In this case, the placement of consumer information, ordering the goods and the transaction take place there, inside the network (on the site of the online store).';
$name_site3 = 'MYFREELANCER';
$site3 = 'Website card';
$description_site3 = 'This complete Internet resource usually consists of a page that contains basic information about the company, its activities, the products or services offered, features and methods of feedback. The competently developed site-business card becomes a business card, effective advertising, a round-the-clock office, the face of the company on the Internet.';
$site4 = 'Landing';
$description_site4 = 'This is a stand-alone Internet site, which a potential customer gets after a click on an advertisement or as a result of a search. Landings are widely used in marketing because of their fundamental difference from the traditional web site.
What are the goals in the Landings? For example, an entry to a webinar, the generation of applications for a particular service or for purchasing a product, downloading an e-book or brochure with tips, subscribing to news and products you offer (buying a product), etc.';

$form_site = '';
$form_site_placeholder = '';
$site_selection = '';
$site_select_1 = '';
$site_select_2 = '';
$site_select_3 = '';
$site_select_4 = '';
$your_data = '';
$your_data_name = '';
$your_data_email = '';
$your_data_tel = '';
$your_data_coment = '';
$form_site_submit = '';
$want_site = 'want site';
$our_works = 'Our works';

$description_work = 'Here you can see the samples works <span style="color: #02d871;">MYFREELANCER</span>';
$name_site1 = 'My <span>Methodist</span>';
$description_name_site1 = 'An informational site, through which you can inform visitors.';
$name_site2 = 'Agro<span>Baza</span>';
$description_name_site2 = 'Online store where direct sales of goods are carried out.';
$name_site3 = 'Hurtova <span>Baza</span>';
$description_name_site3 = 'CRM-system under certain business tasks of the client.';


$argument = 'Why us?';
$argument_description1= 'We are responsibly preparing for our work, because in the answer for it.';
$argument_description2 = 'We have long been working in this field.';
$argument_description3 = 'We do quickly and qualitatively.';

$sequence = 'Sequence of cooperation with us';
$sequence_item_1 = 'You have a need for qualified programmers?';
$sequence_item_1_1 = '';
$sequence_item_1_2 = '';
$sequence_item_2 = "Contact us to discuss your project.";
$sequence_item_2_1 = "";
$sequence_item_3 = 'The team is working on the task.';
$sequence_item_3_1 = '';
$sequence_item_4 = 'Your project testing.';
$sequence_item_4_1 = '';
$sequence_item_5 = 'Site launch and payment.';
$sequence_item_5_1 = '';

$conctakt_form = 'Contact form';
$conctakt_description = 'Here you can ask a question interesting you, or contact us for the order of work.';
$conctakt_name = 'Your name';
$conctakt_email = 'Your email';
$conctakt_comment = 'Your comment';
$conctakt_send = 'Send';

$our_address = 'Our address';
$city1 = 'Kyiv ';
$city2 = 'Rovno';
$phone = 'phone';
$conect = 'Connect with us';

 ?>