<?php 

$slogan = 'молода команда';
$pod_slogan = 'Швидко виконає ваші завдання!';
$learn_more = 'ВЗНАТИ БІЛЬШЕ';

$qualitatively = 'ГАРНА ЯКІСТЬ';
$fast = 'ШВИДКА РОБОТА';
$cheap = 'ДОСТУПНА ЦІНА';

$about = 'Про нас';
$about_bottom = 'Ми молода перспективна команда, яка цілеспрямовано займаєтсья  в сфері "веб-розробка". 	<br> Працюючи з нами ви отримаєте найбільш зручний та сучасний сайт, за короткий час і доступну ціну.';
$site1 = 'Інформаційний сайт';
$description_site1 = 'Інформаційний сайт - це орієнтований на зовнішню аудиторію сайт, який створює присутність організації в мережі Інтернет. Першочерговим завданням такого сайту є представлення бренду організації потенційним клієнтам.';
$site2 = 'Інтернет - магазин';
$description_site2 = 'Це місце в інтернеті, за допомогою якого відбувається прямий продаж товарів споживачеві (юридичній або фізичній особі), враховуючи доставку. При цьому розміщення споживацької інформації, замовлення товару і угода відбуваються там само, всередині мережі (на сайті інтернет-магазину).';
$site3 = 'Сайт - візитка';
$description_site3 = 'Це повноцінний інтернет-ресурс, як правило, складається з сторінки, що містить основну інформацію про компанію, її діяльність, пропоновані товари або послуги, особливості та способи зворотного зв’язку. Грамотно розроблений сайт-візитка стає візитною карткою, ефективною рекламою, цілодобовим офісом, обличчям компанії в Інтернеті.';

$our_works = 'Наші роботи';
$description_work = 'Тут ви можете побачити зразки наших робіт.';
$name_site1 = 'Мій <span>Методист</span>';
$description_name_site1 = 'Інформаційний сайт, за допомогою якого ви можете інформувати відвідувачів.';
$name_site2 = 'Агро <span>База</span>';
$description_name_site2 = 'Інтернет-магазин, де проводиться прямий продаж товарів.';
$name_site3 = 'Гуртова <span>База</span>';
$description_name_site3 = 'CRM-система під певні бізнес-задачі клієнта.';

$argument = 'Чому ми?';
$argument_description1= 'Ми відповідально ставимося до своєї роботи, так як у відповіді за неї.';
$argument_description2 = 'Ми вже довгий час працюємо в цій сфері.';
$argument_description3 = 'Ми робимо швидко і якісно.';

$sequence = 'Послідовність співпраці з нами';
$sequence_item_1 = 'Розуміння про те чи ми вам підходимо?';
$sequence_item_1_1 = 'Жодного випадку про невиконаний до кінця проект.';
$sequence_item_1_2 = 'Після перегляду вами нашого сайта, Ви складаєте аналіз оцінку про те чи саме від нас Вам потрібна робота.';
$sequence_item_2 = "Зв'яжіться з нами!";
$sequence_item_2_1 = "Зв'язаться з нами Ви можете внизу сайта в контактній формі, або ж зателефонавути нам на гарячу лінію.";
$sequence_item_3 = 'Обговорення вашого проета!';
$sequence_item_3_1 = 'Після обговорення з';
$sequence_item_4 = 'Mussum ipsum cacilds';
$sequence_item_4_1 = 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.';
$sequence_item_5 = 'Mussum ipsum cacilds';
$sequence_item_5_1 = 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.';

$conctakt_form = 'Контактна форма';
$conctakt_description = "Тут ви можете задати питання, яке вас цікавить, або ж зв'язатися з нами для замовлення роботи.";
$conctakt_name = " ваше ім'я";
$conctakt_email = ' ваш email';
$conctakt_comment = ' ваш коментар';
$conctakt_send = 'Відправити';

$our_address = 'Наша адреса';
$city1 = 'м. Київ ';
$city2 = 'м. Рівне ';
$phone = 'моб';
$conect = "Зв'язатися з нами";

 ?>